'use client';

import { useEffect, useState, type ComponentType, type ReactNode } from 'react';
import dynamic from 'next/dynamic';
import type { OnMount } from '@monaco-editor/react';
import { cn } from '@lib/utils';

/**
 * ReadOnlyCodeViewer — the shared read-only `@monaco-editor/react` viewer (MFX-43.1, #4361).
 *
 * The export flow shows generated bytes in several places — the Verify and Review steps and the
 * post-generate result — and every one wants the same thing: the emitted document, read-only, syntax
 * highlighted, matching the app's dark/light theme, loaded lazily. This is that one viewer, so those
 * surfaces (and the later bundle tree / diff / markers of MFX-43.2–43.5) share a single Monaco loader
 * rather than each re-deriving it.
 *
 * Monaco is code-split behind {@link https://nextjs.org/docs/app/api-reference/functions/dynamic |
 * next/dynamic} with `ssr: false` (Monaco touches `window`), matching the `ExportWizard.tsx`
 * precedent. If the editor chunk cannot load (offline, blocked CDN) the raw text still renders in a
 * `<pre>` fallback, so the artifact is never hidden behind a failed import.
 */

/** Offline fallback when the Monaco chunk cannot load — keeps the raw text visible and selectable. */
function OfflineCodeFallback({ value, fallbackTestId }: { value?: string; fallbackTestId?: string }) {
  return (
    <pre
      data-testid={fallbackTestId ?? 'read-only-code-content'}
      className="h-full overflow-auto whitespace-pre-wrap break-words p-3 font-mono text-xs leading-5 text-gray-800 dark:text-gray-200"
    >
      {value ?? ''}
    </pre>
  );
}

/** The props the viewer drives Monaco with — a subset of `EditorProps` plus the fallback's test id. */
interface ViewerEditorProps {
  height?: string | number;
  language?: string;
  theme?: string;
  value?: string;
  /** Forwarded by next/dynamic to {@link OfflineCodeFallback} if the editor chunk fails to load. */
  fallbackTestId?: string;
  options?: Record<string, unknown>;
  onMount?: OnMount;
}

/**
 * The one shared Monaco loader for the export viewer surfaces. Declared at module scope so the chunk
 * is fetched once and reused; `.catch` degrades to the offline fallback, `loading` shows a spinner
 * placeholder while the chunk streams in. Typed as {@link ViewerEditorProps} so the `fallbackTestId`
 * next/dynamic passes through to the fallback is accepted (the real `EditorProps` ignore it).
 */
const MonacoEditor = dynamic(
  () =>
    import('@monaco-editor/react')
      .then((mod) => mod.default)
      .catch(() => OfflineCodeFallback),
  {
    ssr: false,
    loading: () => (
      <div className="flex h-full items-center justify-center text-sm text-gray-500 dark:text-gray-400">
        Loading viewer…
      </div>
    ),
  },
) as ComponentType<ViewerEditorProps>;

/** The fixed read-only editor options shared by every export viewer surface. */
const READ_ONLY_OPTIONS = {
  readOnly: true,
  domReadOnly: true,
  minimap: { enabled: false },
  fontSize: 13,
  fontFamily: "'JetBrains Mono', 'Fira Code', Consolas, monospace",
  lineNumbers: 'on' as const,
  scrollBeyondLastLine: false,
  padding: { top: 14, bottom: 14 },
  automaticLayout: true,
  // Markers (squiggles) are suppressed in read-only editors by default; the Verify problem
  // markers (MFX-43.3) need them rendered anyway.
  renderValidationDecorations: 'on' as const,
  renderLineHighlight: 'none' as const,
  overviewRulerLanes: 0,
  hideCursorInOverviewRuler: true,
  contextmenu: false,
  links: false,
  scrollbar: { verticalScrollbarSize: 8, horizontalScrollbarSize: 8 },
};

export interface ReadOnlyCodeViewerProps {
  /** The document text to display. */
  value: string;
  /** The Monaco language id for syntax highlighting (e.g. `protobuf`, `graphql`, `json`). */
  language: string;
  /** Soft-wrap long lines. Defaults to `'off'` (emitted specs are read horizontally). */
  wordWrap?: 'on' | 'off';
  /** Optional control rendered pinned to the editor's top-right (e.g. a copy button). */
  overlay?: ReactNode;
  /** Editor height. Defaults to filling the container (`'100%'`). */
  height?: string | number;
  /** Extra classes for the editor container (borders, background, layout). */
  className?: string;
  /** `data-testid` for the editor container; it also carries `data-language` for assertions. */
  editorTestId?: string;
  /** `data-testid` for the offline `<pre>` fallback. */
  fallbackTestId?: string;
  /**
   * Monaco's mount callback `(editor, monaco) => void`, for callers that decorate the document —
   * the MFX-43.3 problem markers set squiggles/gutter bars and reveal lines through these handles.
   * Never called when the editor chunk fails and the `<pre>` fallback renders instead.
   */
  onMount?: OnMount;
}

/**
 * The shared read-only code viewer. Tracks the app theme by observing the `dark` class Next-Themes
 * toggles on `<html>`, so it flips between Monaco's `vs-dark` and `light` live as the user switches.
 *
 * @param props The document, its language, and presentation options.
 * @returns The read-only Monaco editor (or its offline fallback) in a themed container.
 */
export function ReadOnlyCodeViewer({
  value,
  language,
  wordWrap = 'off',
  overlay,
  height = '100%',
  className,
  editorTestId = 'read-only-code-editor',
  fallbackTestId,
  onMount,
}: ReadOnlyCodeViewerProps) {
  const [isDark, setIsDark] = useState(false);

  useEffect(() => {
    const sync = () => setIsDark(document.documentElement.classList.contains('dark'));
    sync();
    const observer = new MutationObserver(sync);
    observer.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] });
    return () => observer.disconnect();
  }, []);

  return (
    <div
      data-testid={editorTestId}
      data-language={language}
      className={cn('relative overflow-hidden', className)}
    >
      {overlay ? <div className="absolute right-2 top-2 z-10">{overlay}</div> : null}
      {/* Absolute fill: Monaco's `height: 100%` needs a *definite* CSS height on every ancestor,
          which a flex chain sized only by `min-h-*` (the Studio Review step) cannot provide — the
          percentage resolves to 0 and the editor collapses even though the container has a real
          pixel box. Filling that box absolutely sizes the editor from the rendered box instead of
          the CSS height chain, so the viewer works in any bounded container. */}
      <div className="absolute inset-0">
        <MonacoEditor
          height={height}
          language={language}
          theme={isDark ? 'vs-dark' : 'light'}
          value={value}
          fallbackTestId={fallbackTestId}
          options={{ ...READ_ONLY_OPTIONS, wordWrap }}
          onMount={onMount}
        />
      </div>
    </div>
  );
}

export default ReadOnlyCodeViewer;
