/**
 * The `yarn docs:check` gate (DOCS-1.13, #5630): every rule run over the fixture sites in
 * `test/fixtures/gate/` — one that passes, and one per failure the gate must catch — plus the
 * link, orphan and staleness rules on their own.
 */
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import {describe, it} from 'node:test';
import {fileURLToPath} from 'node:url';

import {runGate} from '../scripts/lib/gate.mjs';
import {
  autogeneratedDirs,
  checkOrphans,
  collectRoutes,
  docRoute,
  explicitDocIds,
  findInternalLinks,
  postSlug,
} from '../scripts/lib/links.mjs';
import {
  STALE_AFTER_RELEASES,
  checkStaleScreenshots,
  gitLastChange,
  screenSources,
  staleCutoff,
} from '../scripts/lib/staleness.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const FIXTURES = path.join(here, 'fixtures', 'gate');
const SITE = path.join(here, '..');

/**
 * A {@link LastChange} that reads a fixture's `history.json` (path → commit date) instead of git.
 * A path's date is the latest of the entries at or below it.
 *
 * @param {Record<string, string>} history - Paths relative to the fixture site → ISO dates.
 * @param {string} prefix - What the gate prefixes paths with (the site, relative to the repo root).
 * @returns {(paths: string[]) => Date | null} The lookup.
 */
function fakeHistory(history, prefix = '') {
  return (paths) => {
    const dates = paths.flatMap((wanted) =>
      Object.entries(history)
        .filter(([file]) => {
          const full = prefix ? `${prefix}/${file}` : file;
          return full === wanted || full.startsWith(`${wanted}/`) || (!prefix && file === wanted);
        })
        .map(([, date]) => new Date(date)),
    );
    return dates.length > 0 ? new Date(Math.max(...dates)) : null;
  };
}

/**
 * Run the whole gate over one fixture site.
 *
 * @param {string} name - Fixture folder under `test/fixtures/gate/`.
 * @returns {string[]} The problems.
 */
function gate(name) {
  const siteDir = path.join(FIXTURES, name);
  const history = JSON.parse(fs.readFileSync(path.join(siteDir, 'history.json'), 'utf8'));
  // The gate asks for `<site>/static/img/…` (site relative to the repo root) and for the entry's
  // `sources` as written; the fake answers both.
  const site = fakeHistory(history, name);
  const plain = fakeHistory(history);
  return runGate({siteDir, lastChange: (paths) => site(paths) ?? plain(paths)});
}

describe('the gate over its fixture sites', () => {
  it('passes the valid site', () => {
    assert.deepEqual(gate('valid'), []);
  });

  const cases = [
    ['broken-link', [/page\.mdx: broken link `\.\/publish\.md` — no such file/, /page\.mdx: broken link `\/api-reference`/]],
    ['orphan-page', [/stray\.md: orphan page — move it into a group folder/, /hidden\.md: orphan page — `unlisted: true`/]],
    ['screenshot-one-theme', [/<Screenshot id="home"\/> needs both a light and a dark image/]],
    ['manifest-without-image', [/`settings` has no light image/, /`settings` has no dark image/]],
    ['stale-screenshot', [/`home` was captured 2026-07-01, before RC2, and app\/home changed 2026-09-20/]],
    ['long-description', [/page\.mdx: description is \d+ words; keep it to 14 or fewer/]],
  ];

  for (const [name, expected] of cases) {
    it(`fails ${name}, and only for that`, () => {
      const problems = gate(name);
      assert.equal(problems.length, expected.length, problems.join('\n'));
      for (const pattern of expected) {
        assert.ok(
          problems.some((problem) => pattern.test(problem)),
          `${pattern} not in:\n${problems.join('\n')}`,
        );
      }
    });
  }

  it('every fixture is covered by a case, and documents what it breaks', () => {
    const covered = new Set(['valid', ...cases.map(([name]) => name)]);
    for (const name of fs.readdirSync(FIXTURES)) {
      assert.ok(covered.has(name), `${name} has no test case`);
      assert.ok(fs.existsSync(path.join(FIXTURES, name, 'README.md')), `${name} has no README.md`);
    }
  });

  it('the CLI exits 1 and lists the problem for a failing site, 0 for a passing one', () => {
    const run = (name) =>
      spawnSync(process.execPath, [path.join(SITE, 'scripts', 'check-docs.mjs'), path.join(FIXTURES, name, 'docs')], {
        encoding: 'utf8',
      });
    const failing = run('orphan-page');
    assert.equal(failing.status, 1);
    assert.match(failing.stderr, /docs:check found 2 problem\(s\)/);
    assert.match(failing.stderr, /stray\.md: orphan page/);
    const passing = run('valid');
    assert.equal(passing.status, 0, passing.stderr);
  });
});

describe('internal links', () => {
  it('finds relative and site links in prose, not in code, external URLs or bare anchors', () => {
    const source = [
      'See [a](./a.md#x), [b](/ship), [c](https://example.com), [d](#here) and [e](<../e.mdx>).',
      '`[f](./f.md)`',
      '```md',
      '[g](./g.md)',
      '```',
    ].join('\n');
    assert.deepEqual(findInternalLinks(source), ['./a.md', '/ship', '../e.mdx']);
  });

  it('routes a page by its path, its index, or an absolute slug', () => {
    assert.equal(docRoute('ship/export-a-spec.md', '---\ntitle: x\n---\n'), '/ship/export-a-spec');
    assert.equal(docRoute('ship/index.mdx', '---\ntitle: x\n---\n'), '/ship');
    assert.equal(docRoute('getting-started/index.mdx', '---\nslug: /\n---\n'), '/');
  });

  it('routes a post by its slug, or its file name without the date', () => {
    assert.equal(postSlug('2026-10-07-workspace-pages.mdx', '---\ntitle: x\n---\n'), 'workspace-pages');
    assert.equal(postSlug('rc4.md', '---\nslug: rc4\n---\n'), 'rc4');
  });

  it('collects the real site’s routes, category landing pages and posts included', () => {
    const routes = collectRoutes({docsDir: path.join(SITE, 'docs'), releaseNotesDir: path.join(SITE, 'release-notes')});
    for (const route of ['/', '/ship', '/reference/mock-runtime', '/release-notes', '/release-notes/rc4']) {
      assert.ok(routes.has(route), route);
    }
  });
});

describe('orphan pages', () => {
  it('reads autogenerated folders and hand-listed ids from sidebars.ts', () => {
    const source = `{guide: [{type: 'autogenerated', dirName: 'build'}, {type: 'doc', id: 'ship/publish'}, 'ship/export']}`;
    assert.deepEqual(autogeneratedDirs(source), ['build']);
    assert.deepEqual([...explicitDocIds(source)].sort(), ['ship/export', 'ship/publish']);
  });

  it('flags a page outside every folder and id the sidebar names', () => {
    const docsDir = path.join(FIXTURES, 'valid', 'docs');
    const narrow = `{guide: [{type: 'autogenerated', dirName: 'elsewhere'}, {type: 'doc', id: 'guide/index'}]}`;
    assert.deepEqual(checkOrphans({docsDir, sidebarsSource: narrow}), ['guide/page.mdx: orphan page — no sidebar lists it']);
  });

  it('finds none on the real site', () => {
    const sidebarsSource = fs.readFileSync(path.join(SITE, 'sidebars.ts'), 'utf8');
    assert.deepEqual(checkOrphans({docsDir: path.join(SITE, 'docs'), sidebarsSource}), []);
  });
});

describe('stale screenshots', () => {
  const releases = [
    {name: 'RC1', closed: '2026-06-01'},
    {name: 'RC3', closed: '2026-09-15'},
    {name: 'RC2', closed: '2026-08-01'},
  ];
  const screen = {id: 'home', route: '/ade/dashboard', theme: ['light', 'dark'], sources: ['app/home']};
  const check = (history, options = {}) =>
    checkStaleScreenshots({
      screens: [screen],
      releases,
      lastChange: fakeHistory(history),
      repoRoot: FIXTURES,
      screensPrefix: 'static',
      ...options,
    });

  it(`spans ${STALE_AFTER_RELEASES} releases: the cutoff is that many closes back`, () => {
    assert.equal(staleCutoff(releases, 2).name, 'RC2');
    assert.equal(staleCutoff(releases, 1).name, 'RC3');
    assert.equal(staleCutoff(releases.slice(0, 1), 2), null);
  });

  it('is quiet while there are fewer releases than the span', () => {
    const history = {'static/img/screens/home.light.png': '2026-01-01', 'app/home': '2026-09-30'};
    assert.deepEqual(check(history, {releases: releases.slice(0, 1)}), []);
  });

  it('flags an old image whose sources changed after it, using the older theme', () => {
    const history = {
      'static/img/screens/home.light.png': '2026-09-30T00:00:00Z',
      'static/img/screens/home.dark.png': '2026-07-01T00:00:00Z',
      'app/home/page.tsx': '2026-09-01T00:00:00Z',
    };
    assert.match(check(history)[0], /`home` was captured 2026-07-01, before RC2/);
  });

  it('leaves an old image alone when nothing behind it changed', () => {
    const history = {'static/img/screens/home.light.png': '2026-07-01', 'static/img/screens/home.dark.png': '2026-07-01', 'app/home': '2026-06-15'};
    assert.deepEqual(check(history), []);
  });

  it('leaves a recent image alone, however much changed', () => {
    const history = {'static/img/screens/home.light.png': '2026-08-02', 'static/img/screens/home.dark.png': '2026-08-02', 'app/home': '2026-09-30'};
    assert.deepEqual(check(history), []);
  });

  it('ignores an image with no history (not committed yet)', () => {
    assert.deepEqual(check({'app/home': '2026-09-30'}), []);
  });

  it('defaults an entry’s sources to its route folder under apiome-ui/src/app, when it exists', () => {
    const repoRoot = path.join(SITE, '..');
    assert.deepEqual(screenSources({route: '/ade/dashboard/catalog'}, repoRoot), ['apiome-ui/src/app/ade/dashboard/catalog']);
    assert.deepEqual(screenSources({route: '/ade/dashboard/catalog?view=cards'}, repoRoot), ['apiome-ui/src/app/ade/dashboard/catalog']);
    assert.deepEqual(screenSources({route: '/no/such/route'}, repoRoot), []);
    assert.deepEqual(screenSources({route: '/x', sources: ['a/b']}, repoRoot), ['a/b']);
  });

  it('asks git, and answers null outside a checkout instead of failing', () => {
    const repoRoot = path.join(SITE, '..');
    assert.ok(gitLastChange(repoRoot)(['apiome-docs/package.json']) instanceof Date);
    assert.equal(gitLastChange(repoRoot)([]), null);
    assert.equal(gitLastChange('/')(['nothing-here']), null);
  });
});
