import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

/** The docs plugin's options, as the classic preset takes them. */
type PresetDocsOptions = Exclude<NonNullable<Preset.Options['docs']>, false>;

// This runs in Node.js - don't use client-side code here (browser APIs, JSX...).

/**
 * Where the site is served from.
 *
 * Defaults to the GitHub Pages project site (`https://apiome.github.io/apiome/`). Override
 * with `DOCS_URL` / `DOCS_BASE_URL` to serve it from a custom domain or a sub-path; the
 * base URL must start and end with `/`.
 */
const SITE_URL = process.env.DOCS_URL ?? 'https://apiome.github.io';
const BASE_URL = process.env.DOCS_BASE_URL ?? '/apiome/';

/** The repository the "Edit this page" links and the navbar point at. */
const REPO_URL = 'https://github.com/apiome/apiome';

/** The CLI's pages, which the CLI guide shows and Reference therefore leaves out. */
const CLI_DOC_IDS = new Set(['reference/cli-quickstart', 'reference/cli/index']);

/**
 * Generate a sidebar group from its folder, so that every page sits in exactly one guide.
 *
 * - A folder's own `index` page is the group's link (or, for `getting-started`, the User guide's
 *   home), so it is dropped from the generated list. The CLI reference's index is the exception: it
 *   has no group link to live in, so the CLI guide lists it after the quick-start. (A page's own
 *   `sidebar_label` always wins over a label set here — rename pages in their front matter.)
 * - Reference leaves out the CLI quick-start and the `reference/cli/` category: they form the CLI
 *   guide's sidebar.
 *
 * @param args - Docusaurus's generator arguments, including the default generator.
 * @returns The sidebar items for the `autogenerated` entry being expanded.
 */
const guideSidebarItems: NonNullable<PresetDocsOptions['sidebarItemsGenerator']> = async ({
  defaultSidebarItemsGenerator,
  ...args
}) => {
  const items = await defaultSidebarItemsGenerator(args);
  const ownIndex = `${args.item.dirName}/index`;
  return items.filter((item) => {
    if (item.type === 'doc' && item.id === ownIndex && args.item.dirName !== 'reference/cli') return false;
    if (args.item.dirName !== 'reference') return true;
    if (item.type === 'doc' && CLI_DOC_IDS.has(item.id)) return false;
    if (item.type === 'category' && item.link?.type === 'doc' && CLI_DOC_IDS.has(item.link.id)) return false;
    return true;
  });
};

const config: Config = {
  title: 'Apiome',
  tagline: 'Design, govern and ship APIs — the Apiome documentation',
  favicon: 'img/bee-logo.png',

  future: {
    v4: true,
  },

  url: SITE_URL,
  baseUrl: BASE_URL,
  // GitHub Pages serves `/page` from `page.html`, so URLs carry no trailing slash.
  trailingSlash: false,

  organizationName: 'apiome',
  projectName: 'apiome',

  onBrokenLinks: 'throw',
  onBrokenAnchors: 'throw',
  markdown: {
    // `.md` pages are CommonMark and `.mdx` pages are MDX. The guides migrated from `docs/guide/`
    // (and the pages the REST generators write) are plain Markdown with inline HTML comments
    // (`42<!--format-count:importable-->`) and `<a id>` anchors, which MDX would reject; pages that
    // use components (`<Screenshot/>`, `<Route/>`) are `.mdx`.
    format: 'detect',
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
  },

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  // Inter + JetBrains Mono, self-hosted (no request to a font CDN).
  clientModules: ['./src/fonts.ts'],

  presets: [
    [
      'classic',
      {
        docs: {
          // The guide is the site: docs are served from the root.
          routeBasePath: '/',
          sidebarPath: './sidebars.ts',
          sidebarItemsGenerator: guideSidebarItems,
          editUrl: `${REPO_URL}/tree/main/apiome-docs/`,
        },
        // The blog instance is the release notes (DOCS-1.12).
        blog: {
          path: 'release-notes',
          routeBasePath: 'release-notes',
          blogTitle: 'Release notes',
          blogDescription: 'What changed in each Apiome release.',
          blogSidebarTitle: 'Releases',
          blogSidebarCount: 'ALL',
          showReadingTime: false,
          authorsMapPath: 'authors.yml',
          feedOptions: {
            type: ['rss', 'atom'],
            title: 'Apiome release notes',
          },
          editUrl: `${REPO_URL}/tree/main/apiome-docs/`,
          onInlineTags: 'throw',
          onInlineAuthors: 'throw',
          onUntruncatedBlogPosts: 'ignore',
        },
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themes: [
    [
      '@easyops-cn/docusaurus-search-local',
      {
        hashed: true,
        docsRouteBasePath: '/',
        blogRouteBasePath: '/release-notes',
        blogDir: 'release-notes',
        indexBlog: true,
        highlightSearchTermsOnTargetPage: true,
      },
    ],
  ],

  themeConfig: {
    image: 'img/bee-logo.png',
    colorMode: {
      defaultMode: 'light',
      disableSwitch: false,
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: 'Apiome',
      logo: {
        alt: 'Apiome bee',
        src: 'img/bee-logo.png',
      },
      items: [
        {type: 'docSidebar', sidebarId: 'userGuide', position: 'left', label: 'User guide'},
        {type: 'docSidebar', sidebarId: 'adminGuide', position: 'left', label: 'Administration'},
        {type: 'docSidebar', sidebarId: 'cli', position: 'left', label: 'CLI'},
        {type: 'docSidebar', sidebarId: 'reference', position: 'left', label: 'Reference'},
        {to: '/release-notes', label: 'Release notes', position: 'left'},
        {href: REPO_URL, label: 'GitHub', position: 'right'},
      ],
    },
    footer: {
      style: 'light',
      links: [
        {
          title: 'User guide',
          items: [
            {label: 'Getting started', to: '/'},
            {label: 'Build', to: '/build'},
            {label: 'Ship', to: '/ship'},
            {label: 'Govern', to: '/govern'},
          ],
        },
        {
          title: 'Administration',
          items: [
            {label: 'Administration guide', to: '/admin'},
            {label: 'Operating Apiome', to: '/admin/operating-apiome'},
          ],
        },
        {
          title: 'CLI & reference',
          items: [
            {label: 'CLI', to: '/reference/cli-quickstart'},
            {label: 'Reference', to: '/reference'},
            {label: 'Release notes', to: '/release-notes'},
          ],
        },
        {
          title: 'Project',
          items: [{label: 'GitHub', href: REPO_URL}],
        },
      ],
      copyright: `Copyright © 2021 - 2026 NobuData LLC`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ['bash', 'json', 'yaml'],
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
