import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - don't use client-side code here (browser APIs, JSX...).

/**
 * The guide sidebar, grouped by the job the reader is doing — the same order as the product's
 * navigation rail.
 *
 * Each group is a folder under `docs/` with a `_category_.json` (label, position) and an
 * `index.mdx` that becomes the group's landing page:
 *
 *   Getting started · Build · Bring in · Ship · Govern · Workspace & account · Admin & tools ·
 *   Reference · Release notes
 *
 * Release notes is the blog instance (`release-notes/`), so it is linked rather than generated.
 */
const sidebars: SidebarsConfig = {
  guide: [
    {type: 'autogenerated', dirName: '.'},
    {type: 'link', label: 'Release notes', href: '/release-notes'},
  ],
};

export default sidebars;
