import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The site is four guides, each with its own sidebar and navbar entry:
 *
 * - **User guide** (`userGuide`) — using Apiome, grouped by the job the reader is doing, in the same
 *   order as the product's navigation rail: Getting started · Build · Bring in · Ship · Govern ·
 *   Workspace & account. Its home is the site root (`getting-started/index.mdx`, slug `/`).
 * - **Administration guide** (`adminGuide`) — running an installation: the admin console, the
 *   tools, operating and hosting (`admin/`).
 * - **CLI** (`cli`) — the quick-start and the generated command reference (`reference/cli/`).
 * - **Reference** (`reference`) — REST and MCP reference, the mock runtime, CI actions and the
 *   content voice (`reference/`, without the CLI pages).
 *
 * Release notes is the blog instance (`release-notes/`), linked from the navbar.
 *
 * The folders and their URLs are unchanged — the guides only decide which sidebar a page shows in.
 * Entries are written out literally (no helper): `yarn docs:check`'s orphan-page rule reads the
 * `autogenerated` folders and doc ids straight from this file.
 * Each group is generated from its folder (`_category_.json` for label and position, `index.mdx`
 * as the group's landing page); `sidebarItemsGenerator` in `docusaurus.config.ts` drops the
 * landing page from its own generated list and keeps the CLI pages out of Reference, so every page
 * sits in exactly one sidebar.
 */

const sidebars: SidebarsConfig = {
  userGuide: [
    {type: 'doc', id: 'getting-started/index', label: 'User guide'},
    // The getting-started landing page is the User guide's home (the site root), so this group has
    // no link of its own.
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Build',
      link: {type: 'doc', id: 'build/index'},
      items: [{type: 'autogenerated', dirName: 'build'}],
    },
    {
      type: 'category',
      label: 'Bring in',
      link: {type: 'doc', id: 'bring-in/index'},
      items: [{type: 'autogenerated', dirName: 'bring-in'}],
    },
    {
      type: 'category',
      label: 'Ship',
      link: {type: 'doc', id: 'ship/index'},
      items: [{type: 'autogenerated', dirName: 'ship'}],
    },
    {
      type: 'category',
      label: 'Govern',
      link: {type: 'doc', id: 'govern/index'},
      items: [{type: 'autogenerated', dirName: 'govern'}],
    },
    {
      type: 'category',
      label: 'Workspace & account',
      link: {type: 'doc', id: 'workspace/index'},
      items: [{type: 'autogenerated', dirName: 'workspace'}],
    },
  ],
  // Admin and Reference are one open category each, linked to their landing page, so the
  // landing page's <DocCardList/> lists the guide's pages.
  adminGuide: [
    {
      type: 'category',
      label: 'Administration guide',
      collapsible: false,
      link: {type: 'doc', id: 'admin/index'},
      items: [{type: 'autogenerated', dirName: 'admin'}],
    },
  ],
  cli: [
    {type: 'doc', id: 'reference/cli-quickstart', label: 'Quick-start'},
    {type: 'autogenerated', dirName: 'reference/cli'},
  ],
  reference: [
    {
      type: 'category',
      label: 'Reference',
      collapsible: false,
      link: {type: 'doc', id: 'reference/index'},
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
  ],
};

export default sidebars;
